version: "1.21"

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql:/sql/
    env_file:
      - ./secrets/.env
    ports:
      - "5432:5432"
  bot:
    build: .
    container_name: tg-bot
    command: go run cmd/main.go
    volumes:
      - .:/code
    ports:
      - "8081:8081"
    env_file:
      - ./secrets/.env
    depends_on:
      - db
volumes:
  postgres_data: